"use client";

import { SparklesIcon } from "lucide-react";
import * as React from "react";

import { FormField, controlProps } from "@/components/form/form-field";
import { SubmitButton } from "@/components/form/submit-button";
import { useActionFeedback } from "@/components/form/use-action-feedback";
import { useT } from "@/components/providers/i18n-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { IDLE } from "@/lib/action-state";
import { interpolate } from "@/lib/i18n/format";
import { cn } from "@/lib/utils";
import { generateAssessmentsAction } from "@/modules/assessments/actions";
import { GENERATE_SCOPES, type GenerateScope } from "@/modules/assessments/enums";
import type {
  AssessmentTypeOption,
  ClassOption,
  ProgrammeEntry,
  TermOption,
} from "@/modules/assessments/queries";

/**
 * "Contrôle n°1, semester 1, 3AP-A" → one paper per marked subject.
 *
 * The whole point is that the operator never names the subjects: the programme
 * already knows them, and typing a dozen near-identical forms per class is how
 * a subject quietly goes missing from a report card. Re-running is safe and the
 * dialog says so, because the operator's real question is "did I already do
 * this one?".
 */
export function GenerateDialog({
  classes,
  terms,
  types,
  programmes,
  defaultClassId,
  defaultTermId,
  defaultDate: initialDate,
}: {
  classes: ClassOption[];
  terms: TermOption[];
  types: AssessmentTypeOption[];
  /** Marked subjects per class, so the picker fills in without a round trip. */
  programmes: Record<string, ProgrammeEntry[]>;
  defaultClassId: string | null;
  defaultTermId: string | null;
  /**
   * What the shared date starts at, already clamped into the school year.
   * Today falls outside it for two months a year, and a contrôle dated then
   * belongs to no term at all. See lib/school-year.ts.
   */
  defaultDate: string;
}) {
  const t = useT();
  const [open, setOpen] = React.useState(false);
  const [state, formAction] = React.useActionState(
    generateAssessmentsAction,
    IDLE,
  );

  useActionFeedback(state, { onSuccess: () => setOpen(false) });

  // A closed term cannot take a new paper — the action refuses it, so the
  // picker does not offer it either.
  const openTerms = terms.filter((term) => term.status !== "CLOSED");

  const [classId, setClassId] = React.useState(defaultClassId ?? "");
  const [defaultDate, setDefaultDate] = React.useState(initialDate);

  /**
   * The kind of paper, held rather than left to the form.
   *
   * It decides which half of a split matière is on offer — one contrôle for
   * اللغة العربية, or one devoir per component — so the picker has to re-derive
   * when it changes. See AssessmentType.gradesWholeSubject.
   */
  const [assessmentTypeId, setAssessmentTypeId] = React.useState(
    types[0]?.id ?? "",
  );
  const wholeSubject =
    types.find((type) => type.id === assessmentTypeId)?.gradesWholeSubject ??
    false;

  /**
   * How wide the round is. A level is the ordinary case — 3AP sits the same
   * contrôle n°1 in all three of its classes — and generating class by class is
   * the same dialog filled in eight times, which is where a date gets mistyped.
   */
  const [scope, setScope] = React.useState<GenerateScope>("LEVEL");

  /** The levels, derived from the classes rather than fetched again. */
  const levels = React.useMemo(() => {
    const seen = new Map<string, string>();
    for (const option of classes) {
      if (!seen.has(option.levelOfferingId)) {
        seen.set(option.levelOfferingId, option.levelLabel);
      }
    }
    return [...seen].map(([id, label]) => ({ id, label }));
  }, [classes]);

  const [levelOfferingId, setLevelOfferingId] = React.useState(
    () =>
      classes.find((option) => option.id === defaultClassId)?.levelOfferingId ??
      "",
  );

  /** The classes this run will actually write for. */
  const targetClasses = React.useMemo(() => {
    if (scope === "CLASS") {
      return classes.filter((option) => option.id === classId);
    }
    if (scope === "LEVEL") {
      return classes.filter(
        (option) => option.levelOfferingId === levelOfferingId,
      );
    }
    return classes;
  }, [scope, classes, classId, levelOfferingId]);

  /**
   * The subjects on offer: the union of the target classes' programmes.
   *
   * A union rather than one class's list because two classes of a level can
   * differ — an option taught in one and not the other — and the operator has
   * to be able to tick it. Nothing is over-generated by being generous here:
   * `generateAssessments` writes a subject only where it is genuinely on that
   * class's own programme.
   *
   * Deduplicated on the subject, keeping the first entry that has a teacher, so
   * a subject staffed in one class of the level is offered rather than greyed.
   */
  const programme = React.useMemo(() => {
    const bySubject = new Map<string, ProgrammeEntry>();
    for (const option of targetClasses) {
      for (const entry of programmes[option.id] ?? []) {
        const seen = bySubject.get(entry.subjectId);
        if (!seen || (seen.teacherName === null && entry.teacherName !== null)) {
          bySubject.set(entry.subjectId, entry);
        }
      }
    }
    return [...bySubject.values()];
  }, [programmes, targetClasses]);

  /**
   * What the ticks belong to — changing any of it means a different list.
   *
   * The kind is part of it: switching from a contrôle to a devoir replaces
   * "اللغة العربية" with its four components, and ticks made against the one
   * mean nothing against the other.
   */
  const selectionKey = `${
    scope === "CLASS" ? classId : scope === "LEVEL" ? levelOfferingId : "*"
  }:${assessmentTypeId}`;

  /**
   * What is ticked, and the date on each — kept together with the class it was
   * chosen for.
   *
   * Storing the class alongside the selection is what lets the reset be
   * *derived* rather than synced in an effect: changing class changes the
   * subject list entirely, so the previous ticks mean nothing, and the untouched
   * state for a new class is simply "everything on". An effect that reset it
   * would run a render late and is the sort of thing that shows the wrong list
   * for a frame.
   */
  const [selection, setSelection] = React.useState<{
    key: string;
    chosen: Record<string, string>;
  } | null>(null);

  /**
   * The rows the kind is ordinarily sat on — what "All" ticks, and what the
   * dialog starts with.
   *
   * A contrôle is sat on the matière, so the matières and the subjects that
   * have no components are the rows; a devoir is sat on a component, so the
   * components and the undivided subjects are, and the matière is not offered
   * at all. `componentCount` is what tells the two apart.
   */
  const primary = React.useMemo(
    () =>
      programme.filter((entry) =>
        wholeSubject
          ? entry.parentSubjectId === null
          : entry.componentCount === 0,
      ),
    [programme, wholeSubject],
  );

  /**
   * The programme as the picker shows it: components gathered under the matière
   * they belong to, subjects in their own right on their own.
   *
   * The order of the programme is preserved — it is `LevelSubject.position`,
   * which is the order a report card prints in — so a group appears where its
   * matière does rather than being sorted somewhere else.
   */
  const groups = React.useMemo(() => {
    const byParent: {
      key: string;
      /**
       * The matière, when the kind is sat on it — a row of its own, ticked by
       * default, standing for the whole of اللغة العربية.
       */
      matiere: ProgrammeEntry | null;
      /** The heading a component list sits under, when the matière is not a row. */
      title: string | null;
      entries: ProgrammeEntry[];
    }[] = [];
    const index = new Map<string, number>();

    for (const entry of programme) {
      const key = entry.parentSubjectId ?? entry.subjectId;

      if (index.get(key) === undefined) {
        index.set(key, byParent.length);
        byParent.push({
          key,
          matiere: null,
          // Null for a matière with no components: it needs no heading, it *is*
          // the row.
          title: entry.parentSubjectName,
          entries: [],
        });
      }
      const group = byParent[index.get(key)!];

      if (entry.componentCount === 0) {
        group.entries.push(entry);
      } else if (wholeSubject) {
        // The kind is sat on the matière, so it is a row of its own.
        group.matiere = entry;
      } else {
        // It is not sat directly — it only names the components below it.
        group.title = entry.subjectName;
      }
    }

    return byParent;
  }, [programme, wholeSubject]);

  /** A subject nobody teaches cannot be generated — the action refuses it. */
  const staffed = primary.filter((entry) => entry.teacherName !== null);
  const unstaffedCount = primary.length - staffed.length;

  /** Whether any matière is split, so the note about components is worth making. */
  const hasComponents = programme.some((entry) => entry.componentCount > 0);

  const everythingOn = (subjects: ProgrammeEntry[], date: string) =>
    Object.fromEntries(subjects.map((entry) => [entry.subjectId, date]));

  // Untouched means "every subject that has a teacher" — the unstaffed ones
  // start off because ticking them could not produce anything.
  const chosen =
    selection?.key === selectionKey
      ? selection.chosen
      : everythingOn(staffed, defaultDate);

  const setChosen = (chosenNext: Record<string, string>) =>
    setSelection({ key: selectionKey, chosen: chosenNext });

  /**
   * Ticks one row, and unticks whatever it is an alternative to.
   *
   * A matière and its own components are two ways of marking the same work, so
   * they are mutually exclusive: ticking اللغة العربية drops الإملاء, and
   * ticking الإملاء drops اللغة العربية. Generating both would put the matière
   * on the report card twice. The service enforces the same rule — a Server
   * Function is reachable by direct POST — but doing it here is what makes the
   * screen honest about what will be written.
   */
  function toggle(entry: ProgrammeEntry, checked: boolean) {
    const next = { ...chosen };

    if (!checked) {
      delete next[entry.subjectId];
      setChosen(next);
      return;
    }

    next[entry.subjectId] = defaultDate;
    if (entry.componentCount > 0) {
      for (const other of programme) {
        if (other.parentSubjectId === entry.subjectId) delete next[other.subjectId];
      }
    } else if (entry.parentSubjectId) {
      delete next[entry.parentSubjectId];
    }

    setChosen(next);
  }

  function setAll(checked: boolean) {
    setChosen(checked ? everythingOn(staffed, defaultDate) : {});
  }

  /** Retyping the shared date moves every paper that still carries the old one. */
  function applyDefaultDate(value: string) {
    const next: Record<string, string> = {};
    for (const [subjectId, date] of Object.entries(chosen)) {
      next[subjectId] = date === defaultDate ? value : date;
    }
    setChosen(next);
    setDefaultDate(value);
  }

  const chosenCount = Object.keys(chosen).length;

  const disabled =
    classes.length === 0 || openTerms.length === 0 || types.length === 0;

  /**
   * One tickable subject, with its own date.
   *
   * Shared by the matière row and the component rows under it: they differ only
   * in indentation, and giving them two renderers is how the two quietly stop
   * behaving the same.
   */
  function renderRow(entry: ProgrammeEntry, indented: boolean) {
    const checked = entry.subjectId in chosen;
    // No teacher, no paper — the action refuses it, so the row cannot be ticked
    // and says why.
    const blocked = entry.teacherName === null;

    return (
      <div
        key={entry.subjectId}
        className={cn(
          "flex items-center gap-3 p-2",
          indented && "ps-6",
          blocked && "opacity-60",
        )}
      >
        <Checkbox
          id={`subject-${entry.subjectId}`}
          checked={checked}
          disabled={blocked}
          onCheckedChange={(value) => toggle(entry, value === true)}
        />
        <Label
          htmlFor={`subject-${entry.subjectId}`}
          className="min-w-0 flex-1 cursor-pointer text-sm font-normal"
        >
          <span className="truncate">{entry.subjectName}</span>
          <span className="text-muted-foreground ms-1.5 text-xs">
            ×{entry.coefficient}
          </span>
          <span
            className={cn(
              "block truncate text-xs",
              blocked ? "text-warning" : "text-muted-foreground",
            )}
          >
            {entry.teacherName ?? t.assessment.noTeacher}
          </span>
        </Label>
        <Input
          type="date"
          value={chosen[entry.subjectId] ?? ""}
          onChange={(event) =>
            setChosen({ ...chosen, [entry.subjectId]: event.target.value })
          }
          // A date on an unticked subject would be a promise the generator will
          // not keep.
          disabled={!checked}
          dir="ltr"
          className="h-8 w-36 text-xs"
          aria-label={`${entry.subjectName} — ${t.assessment.scheduledOn}`}
        />
      </div>
    );
  }

  return (
    <>
      <Button onClick={() => setOpen(true)} disabled={disabled}>
        <SparklesIcon />
        {t.assessment.generate}
      </Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl">
          <form action={formAction}>
            <DialogHeader>
              <DialogTitle>{t.assessment.generateTitle}</DialogTitle>
              <DialogDescription className="text-pretty">
                {t.assessment.generateHint}
              </DialogDescription>
            </DialogHeader>

            <div className="grid gap-4 py-4">
              {/* The scope travels as a hidden field with the two ids beside
                it; the action decides which of them it reads. */}
              <input type="hidden" name="scope" value={scope} />

              <FormField
                name="scope"
                label={t.assessment.scope}
                hint={t.assessment.scopeHint}
              >
                <Select
                  value={scope}
                  onValueChange={(value) => setScope(value as GenerateScope)}
                >
                  <SelectTrigger id="scope" className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {GENERATE_SCOPES.map((option) => (
                      <SelectItem key={option} value={option}>
                        {option === "CLASS"
                          ? t.assessment.scopeClass
                          : option === "LEVEL"
                            ? t.assessment.scopeLevel
                            : t.assessment.scopeYear}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </FormField>

              {scope === "CLASS" ? (
                <FormField name="schoolClassId" label={t.assessment.class}>
                  <Select
                    name="schoolClassId"
                    value={classId}
                    onValueChange={setClassId}
                  >
                    <SelectTrigger id="schoolClassId" className="w-full">
                      <SelectValue placeholder={t.assessment.class} />
                    </SelectTrigger>
                    <SelectContent>
                      {classes.map((option) => (
                        <SelectItem key={option.id} value={option.id}>
                          {option.code} · {option.levelLabel}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </FormField>
              ) : null}

              {scope === "LEVEL" ? (
                <FormField name="levelOfferingId" label={t.assessment.pickLevel}>
                  <Select
                    name="levelOfferingId"
                    value={levelOfferingId}
                    onValueChange={setLevelOfferingId}
                  >
                    <SelectTrigger id="levelOfferingId" className="w-full">
                      <SelectValue placeholder={t.assessment.pickLevel} />
                    </SelectTrigger>
                    <SelectContent>
                      {levels.map((level) => (
                        <SelectItem key={level.id} value={level.id}>
                          {level.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </FormField>
              ) : null}

              {/* What the run will actually cover, said plainly: the count is
                the thing an operator checks before pressing the button. */}
              <p className="text-muted-foreground text-xs">
                {interpolate(t.assessment.willCover, {
                  classes: targetClasses.length,
                  subjects: chosenCount,
                })}
              </p>

              <FormField name="termId" label={t.assessment.term}>
                <Select name="termId" defaultValue={defaultTermId ?? undefined}>
                  <SelectTrigger id="termId" className="w-full">
                    <SelectValue placeholder={t.assessment.term} />
                  </SelectTrigger>
                  <SelectContent>
                    {openTerms.map((term) => (
                      <SelectItem key={term.id} value={term.id}>
                        {term.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </FormField>

              <FormField name="assessmentTypeId" label={t.assessment.kind}>
                <Select
                  name="assessmentTypeId"
                  value={assessmentTypeId}
                  onValueChange={setAssessmentTypeId}
                >
                  <SelectTrigger id="assessmentTypeId" className="w-full">
                    <SelectValue placeholder={t.assessment.kind} />
                  </SelectTrigger>
                  <SelectContent>
                    {types.map((type) => (
                      <SelectItem key={type.id} value={type.id}>
                        {type.name} · /{type.defaultMaxScore} · ×
                        {type.defaultCoefficient}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </FormField>

              <div className="grid gap-4 sm:grid-cols-2">
                <FormField
                  name="sequence"
                  label={t.assessment.sequence}
                  hint={t.assessment.sequenceHint}
                  error={state.fieldErrors?.sequence}
                >
                  <Input
                    {...controlProps("sequence", state.fieldErrors?.sequence)}
                    type="number"
                    min={1}
                    max={20}
                    defaultValue={1}
                    dir="ltr"
                  />
                </FormField>

                <FormField
                  name="scheduledOn"
                  label={t.assessment.scheduledOn}
                  error={state.fieldErrors?.scheduledOn}
                >
                  <Input
                    {...controlProps(
                      "scheduledOn",
                      state.fieldErrors?.scheduledOn,
                    )}
                    type="date"
                    value={defaultDate}
                    onChange={(event) => applyDefaultDate(event.target.value)}
                    dir="ltr"
                  />
                </FormField>
              </div>

              {/*
                The subject picker. Every ticked row posts a `subjectId:date`
                pair, so each paper carries its own date — which is the whole
                point: a round of contrôles is sat across a week, and the one
                thing the old all-or-nothing generator could not express was
                "everything except EPS, and Maths on the Thursday".
              */}
              <div className="grid gap-2">
                <div className="flex flex-wrap items-center gap-2">
                  <Label className="flex-1">
                    {t.assessment.subjectsToGenerate}
                    {/* Ticked, without a denominator: a component ticked in
                      place of its matière swaps one row for another, so there
                      is no single total to count against. */}
                    <Badge variant="secondary" className="ms-1.5 tabular-nums">
                      {chosenCount}
                    </Badge>
                  </Label>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={() => setAll(true)}
                  >
                    {t.assessment.allSubjects}
                  </Button>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={() => setAll(false)}
                  >
                    {t.assessment.noneSubjects}
                  </Button>
                </div>
                <p className="text-muted-foreground text-xs text-pretty">
                  {t.assessment.subjectsToGenerateHint}
                </p>

                {/* Said only where a matière is actually split, and only where
                  the kind is sat on it — otherwise it describes nothing on
                  screen. */}
                {wholeSubject && hasComponents ? (
                  <p className="text-muted-foreground text-xs text-pretty">
                    {t.assessment.wholeSubjectHint}
                  </p>
                ) : null}

                {unstaffedCount > 0 ? (
                  <p className="text-warning text-xs text-pretty">
                    {interpolate(t.assessment.unstaffedSubjects, {
                      count: unstaffedCount,
                    })}
                  </p>
                ) : null}

                {programme.length === 0 ? (
                  <p className="text-muted-foreground py-4 text-center text-sm">
                    {t.assessment.noProgramme}
                  </p>
                ) : (
                  <div className="max-h-80 overflow-y-auto rounded-lg border">
                    {groups.map((group) => (
                      <div key={group.key} className="border-b last:border-b-0">
                        {/* A matière the kind is *not* sat on is a heading over
                          its components; one it is sat on is a row, rendered
                          below with the rest. */}
                        {group.title ? (
                          <p className="bg-muted/50 text-muted-foreground px-2 py-1 text-xs font-medium">
                            {group.title}
                          </p>
                        ) : null}

                        {group.matiere ? renderRow(group.matiere, false) : null}

                        {/* Under a matière that is itself a row, the components
                          are the exception — offered, but off unless asked for. */}
                        {group.matiere && group.entries.length > 0 ? (
                          <p className="text-muted-foreground px-2 pt-1 ps-9 text-xs">
                            {t.assessment.orOneComponent}
                          </p>
                        ) : null}

                        {group.entries.map((entry) =>
                          renderRow(entry, Boolean(group.title || group.matiere)),
                        )}
                      </div>
                    ))}
                  </div>
                )}

                {Object.entries(chosen).map(([subjectId, date]) => (
                  <input
                    key={subjectId}
                    type="hidden"
                    name="target"
                    value={`${subjectId}:${date}`}
                  />
                ))}
              </div>
            </div>

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={() => setOpen(false)}
              >
                {t.common.cancel}
              </Button>
              <SubmitButton disabled={chosenCount === 0}>
                <SparklesIcon />
                {t.assessment.generate}
              </SubmitButton>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </>
  );
}
