import { EDUCATION_CYCLES } from "@/modules/academics/enums";
import {
  BILLING_CYCLES,
  DISCOUNT_KINDS,
  DISCOUNT_REASONS,
  FEE_KINDS,
} from "@/modules/billing/enums";
import { GROUP_PURPOSES } from "@/modules/classes/enums";
import { ROOM_KINDS } from "@/modules/facilities/enums";
import { TERM_STATUSES } from "@/modules/school-years/enums";
import { DAY_SESSIONS, SCHEDULE_KINDS, TEACHING_DAYS } from "@/modules/timetable/enums";
import type { ResourceDef, SectionDef } from "@/modules/configuration/types";

/**
 * Every configurable table, described once.
 *
 * Adding a configuration screen is adding an entry here — the tabs, the table,
 * the create/edit dialog, the validation and the delete confirmation are all
 * generated from it. Nothing else needs editing except the labels in `i18n/`.
 *
 * Client-safe: this file is imported by the dialog to build its form. The
 * database side of a resource (what it scopes to, what it injects on create)
 * lives in `schema.server.ts`, keyed by the same `id`.
 */

/** Top-level horizontal tabs, in order. */
export const SECTIONS: SectionDef[] = [
  { id: "academics", labelKey: "academics" },
  { id: "facilities", labelKey: "facilities" },
  { id: "year", labelKey: "year" },
  { id: "classes", labelKey: "classes" },
  { id: "billing", labelKey: "billing" },
];

/** Shared trailing fields — every resource that has them wants them last. */
const IS_ACTIVE = {
  name: "isActive",
  type: "boolean",
  labelKey: "isActive",
  defaultValue: true,
  inTable: true,
} as const;

const POSITION = {
  name: "position",
  type: "number",
  labelKey: "position",
  hintKey: "position",
  min: 0,
  defaultValue: 0,
} as const;

const NAME_AR = {
  name: "nameAr",
  type: "text",
  labelKey: "nameAr",
  maxLength: 120,
} as const;

const MASSAR_CODE = {
  name: "massarCode",
  type: "text",
  labelKey: "massarCode",
  hintKey: "massarCode",
  maxLength: 32,
  dir: "ltr",
  inTable: true,
} as const;

/** Vertical tabs within each section, in order. */
export const RESOURCES: ResourceDef[] = [
  // ── Structure pédagogique ─────────────────────────────────────────────────
  {
    id: "education-levels",
    section: "academics",
    labelKey: "educationLevels",
    scope: "SCHOOL",
    labelFields: ["name"],
    fields: [
      {
        name: "cycle",
        type: "select",
        labelKey: "cycle",
        options: EDUCATION_CYCLES,
        optionsKey: "cycles",
        required: true,
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", required: true, maxLength: 120, inTable: true },
      NAME_AR,
      POSITION,
      IS_ACTIVE,
    ],
  },
  {
    id: "levels",
    section: "academics",
    labelKey: "levels",
    scope: "SCHOOL",
    labelFields: ["code", "name"],
    fields: [
      {
        name: "educationLevelId",
        type: "reference",
        labelKey: "educationLevel",
        referenceTo: "education-levels",
        required: true,
        inTable: true,
      },
      {
        name: "code",
        type: "text",
        labelKey: "code",
        hintKey: "levelCode",
        required: true,
        maxLength: 16,
        dir: "ltr",
        placeholder: "2BAC",
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", required: true, maxLength: 120, inTable: true },
      NAME_AR,
      {
        name: "gradeYear",
        type: "number",
        labelKey: "gradeYear",
        hintKey: "gradeYear",
        required: true,
        min: 1,
        max: 12,
        defaultValue: 1,
      },
      MASSAR_CODE,
      POSITION,
      IS_ACTIVE,
    ],
  },
  {
    id: "tracks",
    section: "academics",
    labelKey: "tracks",
    scope: "SCHOOL",
    labelFields: ["code", "name"],
    fields: [
      {
        name: "levelId",
        type: "reference",
        labelKey: "level",
        hintKey: "trackLevel",
        referenceTo: "levels",
        required: true,
        inTable: true,
      },
      {
        name: "code",
        type: "text",
        labelKey: "code",
        required: true,
        maxLength: 16,
        dir: "ltr",
        placeholder: "SM-A",
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", required: true, maxLength: 120, inTable: true },
      NAME_AR,
      MASSAR_CODE,
      POSITION,
      IS_ACTIVE,
    ],
  },
  {
    id: "subjects",
    section: "academics",
    labelKey: "subjects",
    scope: "SCHOOL",
    labelFields: ["code", "name"],
    fields: [
      {
        name: "code",
        type: "text",
        labelKey: "code",
        required: true,
        maxLength: 16,
        dir: "ltr",
        placeholder: "MATH",
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", required: true, maxLength: 120, inTable: true },
      NAME_AR,
      { name: "shortName", type: "text", labelKey: "shortName", maxLength: 16 },
      {
        name: "parentId",
        type: "reference",
        labelKey: "parentSubject",
        hintKey: "parentSubject",
        referenceTo: "subjects",
        nullable: true,
        inTable: true,
      },
      MASSAR_CODE,
      { name: "colorHex", type: "color", labelKey: "colorHex" },
      { name: "isLanguage", type: "boolean", labelKey: "isLanguage" },
      { name: "requiresLab", type: "boolean", labelKey: "requiresLab" },
      IS_ACTIVE,
    ],
  },
  {
    id: "assessment-types",
    section: "academics",
    labelKey: "assessmentTypes",
    scope: "SCHOOL",
    labelFields: ["code", "name"],
    fields: [
      {
        name: "code",
        type: "text",
        labelKey: "code",
        required: true,
        maxLength: 16,
        dir: "ltr",
        placeholder: "CC",
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", required: true, maxLength: 120, inTable: true },
      NAME_AR,
      {
        name: "defaultCoefficient",
        type: "number",
        labelKey: "defaultCoefficient",
        hintKey: "defaultCoefficient",
        min: 1,
        max: 20,
        defaultValue: 1,
        inTable: true,
      },
      {
        name: "defaultMaxScore",
        type: "number",
        labelKey: "defaultMaxScore",
        hintKey: "defaultMaxScore",
        min: 1,
        max: 100,
        defaultValue: 20,
        inTable: true,
      },
      {
        name: "countsTowardAverage",
        type: "boolean",
        labelKey: "countsTowardAverage",
        hintKey: "countsTowardAverage",
        defaultValue: true,
        inTable: true,
      },
      {
        name: "allowTeacherCreate",
        type: "boolean",
        labelKey: "allowTeacherCreate",
        hintKey: "allowTeacherCreate",
        defaultValue: false,
        inTable: true,
      },
      { name: "colorHex", type: "color", labelKey: "colorHex" },
      POSITION,
      IS_ACTIVE,
    ],
  },
  {
    id: "programme",
    section: "academics",
    labelKey: "programme",
    scope: "SCHOOL",
    labelFields: ["coefficient"],
    fields: [
      {
        name: "levelId",
        type: "reference",
        labelKey: "level",
        referenceTo: "levels",
        required: true,
        inTable: true,
      },
      {
        name: "trackId",
        type: "reference",
        labelKey: "track",
        hintKey: "programmeTrack",
        referenceTo: "tracks",
        nullable: true,
        inTable: true,
      },
      {
        name: "subjectId",
        type: "reference",
        labelKey: "subject",
        referenceTo: "subjects",
        required: true,
        inTable: true,
      },
      {
        name: "coefficient",
        type: "number",
        labelKey: "coefficient",
        hintKey: "coefficient",
        required: true,
        min: 1,
        max: 20,
        defaultValue: 1,
        inTable: true,
      },
      {
        name: "weeklyMinutes",
        type: "number",
        labelKey: "weeklyMinutes",
        hintKey: "weeklyMinutes",
        min: 0,
        max: 3000,
        inTable: true,
      },
      { name: "isGraded", type: "boolean", labelKey: "isGraded", defaultValue: true },
      { name: "isEliminatory", type: "boolean", labelKey: "isEliminatory" },
      POSITION,
    ],
  },

  // ── Établissement ─────────────────────────────────────────────────────────
  {
    id: "rooms",
    section: "facilities",
    labelKey: "rooms",
    scope: "SCHOOL",
    labelFields: ["code", "name"],
    fields: [
      {
        name: "code",
        type: "text",
        labelKey: "code",
        required: true,
        maxLength: 32,
        dir: "ltr",
        placeholder: "B12",
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", maxLength: 120, inTable: true },
      {
        name: "kind",
        type: "select",
        labelKey: "roomKind",
        options: ROOM_KINDS,
        optionsKey: "roomKinds",
        defaultValue: "CLASSROOM",
        required: true,
        inTable: true,
      },
      { name: "building", type: "text", labelKey: "building", maxLength: 80, inTable: true },
      { name: "floor", type: "number", labelKey: "floor", min: -5, max: 50 },
      { name: "capacity", type: "number", labelKey: "capacity", min: 0, max: 2000, inTable: true },
      IS_ACTIVE,
      { name: "notes", type: "textarea", labelKey: "notes", maxLength: 500, wide: true },
    ],
  },

  // ── Année scolaire ────────────────────────────────────────────────────────
  {
    id: "terms",
    section: "year",
    labelKey: "terms",
    scope: "YEAR",
    labelFields: ["name"],
    fields: [
      {
        name: "number",
        type: "number",
        labelKey: "termNumber",
        hintKey: "termNumber",
        required: true,
        min: 1,
        max: 3,
        defaultValue: 1,
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", required: true, maxLength: 60, inTable: true },
      NAME_AR,
      { name: "startDate", type: "date", labelKey: "startDate", required: true, inTable: true },
      { name: "endDate", type: "date", labelKey: "endDate", required: true, inTable: true },
      {
        name: "status",
        type: "select",
        labelKey: "status",
        options: TERM_STATUSES,
        optionsKey: "termStatuses",
        defaultValue: "PLANNED",
        required: true,
        inTable: true,
      },
    ],
  },
  {
    id: "time-slots",
    section: "year",
    labelKey: "timeSlots",
    scope: "YEAR",
    labelFields: ["startTime", "endTime"],
    fields: [
      {
        name: "dayOfWeek",
        type: "select",
        labelKey: "dayOfWeek",
        hintKey: "dayOfWeek",
        options: TEACHING_DAYS.map(String),
        optionsKey: "days",
        defaultValue: "1",
        required: true,
        inTable: true,
      },
      {
        name: "session",
        type: "select",
        labelKey: "session",
        options: DAY_SESSIONS,
        optionsKey: "sessions",
        defaultValue: "MORNING",
        required: true,
        inTable: true,
      },
      { name: "startTime", type: "time", labelKey: "startTime", required: true, dir: "ltr", inTable: true },
      { name: "endTime", type: "time", labelKey: "endTime", required: true, dir: "ltr", inTable: true },
      {
        name: "scheduleKind",
        type: "select",
        labelKey: "scheduleKind",
        hintKey: "scheduleKind",
        options: SCHEDULE_KINDS,
        optionsKey: "scheduleKinds",
        defaultValue: "STANDARD",
        required: true,
        inTable: true,
      },
      { name: "isBreak", type: "boolean", labelKey: "isBreak", hintKey: "isBreak" },
      POSITION,
      IS_ACTIVE,
    ],
  },

  // ── Classes ───────────────────────────────────────────────────────────────
  {
    id: "level-offerings",
    section: "classes",
    labelKey: "levelOfferings",
    scope: "YEAR",
    labelFields: ["id"],
    fields: [
      {
        name: "levelId",
        type: "reference",
        labelKey: "level",
        referenceTo: "levels",
        required: true,
        inTable: true,
      },
      {
        name: "trackId",
        type: "reference",
        labelKey: "track",
        hintKey: "offeringTrack",
        referenceTo: "tracks",
        nullable: true,
        inTable: true,
      },
      {
        name: "plannedCapacity",
        type: "number",
        labelKey: "plannedCapacity",
        hintKey: "plannedCapacity",
        min: 0,
        max: 5000,
        inTable: true,
      },
      IS_ACTIVE,
    ],
  },
  {
    id: "classes",
    section: "classes",
    labelKey: "schoolClasses",
    scope: "YEAR",
    labelFields: ["code"],
    fields: [
      {
        name: "levelOfferingId",
        type: "reference",
        labelKey: "levelOffering",
        referenceTo: "level-offerings",
        required: true,
        inTable: true,
      },
      {
        name: "code",
        type: "text",
        labelKey: "code",
        required: true,
        maxLength: 32,
        dir: "ltr",
        placeholder: "2BAC-SM-A-1",
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", maxLength: 120 },
      { name: "section", type: "text", labelKey: "section", maxLength: 8, dir: "ltr", inTable: true },
      { name: "capacity", type: "number", labelKey: "capacity", min: 0, max: 200, inTable: true },
      {
        name: "mainTeacherId",
        type: "reference",
        labelKey: "mainTeacher",
        hintKey: "mainTeacher",
        referenceTo: "@teachers",
        nullable: true,
        inTable: true,
      },
      {
        name: "roomId",
        type: "reference",
        labelKey: "room",
        hintKey: "classRoom",
        referenceTo: "rooms",
        nullable: true,
        inTable: true,
      },
      IS_ACTIVE,
    ],
  },
  {
    id: "class-groups",
    section: "classes",
    labelKey: "classGroups",
    scope: "YEAR",
    labelFields: ["code"],
    fields: [
      {
        name: "schoolClassId",
        type: "reference",
        labelKey: "schoolClass",
        referenceTo: "classes",
        required: true,
        inTable: true,
      },
      {
        name: "code",
        type: "text",
        labelKey: "code",
        required: true,
        maxLength: 16,
        dir: "ltr",
        placeholder: "G1",
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", maxLength: 120, inTable: true },
      {
        name: "purpose",
        type: "select",
        labelKey: "purpose",
        options: GROUP_PURPOSES,
        optionsKey: "groupPurposes",
        defaultValue: "OTHER",
        required: true,
        inTable: true,
      },
      {
        name: "subjectId",
        type: "reference",
        labelKey: "subject",
        hintKey: "groupSubject",
        referenceTo: "subjects",
        nullable: true,
        inTable: true,
      },
      { name: "capacity", type: "number", labelKey: "capacity", min: 0, max: 200 },
      IS_ACTIVE,
    ],
  },

  // ── Facturation ───────────────────────────────────────────────────────────
  {
    id: "fee-types",
    section: "billing",
    labelKey: "feeTypes",
    scope: "SCHOOL",
    labelFields: ["code", "name"],
    fields: [
      {
        name: "code",
        type: "text",
        labelKey: "code",
        required: true,
        maxLength: 32,
        dir: "ltr",
        placeholder: "SCOLARITE",
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", required: true, maxLength: 120, inTable: true },
      NAME_AR,
      {
        name: "kind",
        type: "select",
        labelKey: "feeKind",
        options: FEE_KINDS,
        optionsKey: "feeKinds",
        defaultValue: "OTHER",
        required: true,
        inTable: true,
      },
      {
        name: "billingCycle",
        type: "select",
        labelKey: "billingCycle",
        hintKey: "billingCycle",
        options: BILLING_CYCLES,
        optionsKey: "billingCycles",
        defaultValue: "ANNUAL",
        required: true,
        inTable: true,
      },
      {
        name: "isMandatory",
        type: "boolean",
        labelKey: "isMandatory",
        hintKey: "isMandatory",
        defaultValue: true,
        inTable: true,
      },
      POSITION,
      IS_ACTIVE,
    ],
  },
  {
    id: "fee-rates",
    section: "billing",
    labelKey: "feeRates",
    scope: "YEAR",
    labelFields: ["amountCentimes"],
    fields: [
      {
        name: "feeTypeId",
        type: "reference",
        labelKey: "feeType",
        referenceTo: "fee-types",
        required: true,
        inTable: true,
      },
      {
        name: "levelId",
        type: "reference",
        labelKey: "level",
        hintKey: "feeRateLevel",
        referenceTo: "levels",
        nullable: true,
        inTable: true,
      },
      {
        name: "amountCentimes",
        type: "money",
        labelKey: "amount",
        hintKey: "amount",
        required: true,
        min: 0,
        inTable: true,
      },
      {
        name: "instalmentCount",
        type: "number",
        labelKey: "instalmentCount",
        hintKey: "instalmentCount",
        min: 1,
        max: 12,
        inTable: true,
      },
      IS_ACTIVE,
      { name: "notes", type: "textarea", labelKey: "notes", maxLength: 500, wide: true },
    ],
  },
  {
    id: "discounts",
    section: "billing",
    labelKey: "discounts",
    scope: "YEAR",
    labelFields: ["code", "name"],
    fields: [
      {
        name: "code",
        type: "text",
        labelKey: "code",
        required: true,
        maxLength: 32,
        dir: "ltr",
        placeholder: "FRATRIE-2",
        inTable: true,
      },
      { name: "name", type: "text", labelKey: "name", required: true, maxLength: 120, inTable: true },
      NAME_AR,
      {
        name: "kind",
        type: "select",
        labelKey: "discountKind",
        hintKey: "discountKind",
        options: DISCOUNT_KINDS,
        optionsKey: "discountKinds",
        defaultValue: "PERCENTAGE",
        required: true,
        inTable: true,
      },
      {
        name: "percentBps",
        type: "number",
        labelKey: "percentBps",
        hintKey: "percentBps",
        min: 0,
        max: 10000,
        inTable: true,
      },
      { name: "amountCentimes", type: "money", labelKey: "amount", min: 0, inTable: true },
      {
        name: "reason",
        type: "select",
        labelKey: "discountReason",
        options: DISCOUNT_REASONS,
        optionsKey: "discountReasons",
        defaultValue: "OTHER",
        required: true,
        inTable: true,
      },
      {
        name: "feeTypeId",
        type: "reference",
        labelKey: "feeType",
        hintKey: "discountFeeType",
        referenceTo: "fee-types",
        nullable: true,
        inTable: true,
      },
      { name: "isStackable", type: "boolean", labelKey: "isStackable", hintKey: "isStackable" },
      IS_ACTIVE,
      { name: "notes", type: "textarea", labelKey: "notes", maxLength: 500, wide: true },
    ],
  },
];

export function findResource(id: string): ResourceDef | undefined {
  return RESOURCES.find((resource) => resource.id === id);
}

export function resourcesInSection(sectionId: string): ResourceDef[] {
  return RESOURCES.filter((resource) => resource.section === sectionId);
}

export function findSection(id: string): SectionDef | undefined {
  return SECTIONS.find((section) => section.id === id);
}
