import { defineModule } from "@/lib/module";
import { MASSAR_PERMISSIONS } from "@/modules/massar/permissions";

/**
 * MASSAR — the ministry's own system, and the notes that travel to and from it.
 *
 * Owns no tables. A mark sheet arriving from MASSAR becomes an `Assessment` and
 * its `AssessmentGrade`s, written through `modules/assessments`' own service so
 * the scale, the status rules and the audit trail are the ones the mark sheet
 * screen already enforces. What this module contributes is the *reconciliation*:
 * deciding that a file the ministry produced is about a class this school
 * actually has, and refusing to write anything until it is.
 *
 * It sits apart from `imports` on purpose. That module loads a school's own
 * spreadsheet of pupils, forgivingly, because the school typed it. This one
 * reads a file generated by another system that will read it back, and the
 * governing rule is the opposite: nothing is guessed, and the workbook goes home
 * in the shape it arrived in.
 *
 * The two identifying columns it needs — `Student.massarNumber` and
 * `Assessment.massarCode` — live on their owners' tables rather than in a
 * mapping table here, because they are facts about the pupil and the contrôle
 * and stay true whether or not anybody ever opens this screen.
 */
export const massarModule = defineModule({
  id: "massar",
  nav: [
    {
      href: "/massar",
      icon: "massar",
      section: "vieScolaire",
      labelKey: "massar",
      // Straight after the contrôles: this is where their marks come from and
      // go back to, and it means nothing to somebody who has not seen those.
      order: 46,
      schoolPermission: MASSAR_PERMISSIONS.MASSAR_RECONCILE,
    },
  ],
  permissions: [{ group: "massar", codes: Object.values(MASSAR_PERMISSIONS) }],
});
