import { PERMISSIONS } from "@/lib/permissions";
import type { ReportDef } from "@/modules/reports/types";

/**
 * Every report the school can run, described once.
 *
 * ── Why a catalogue rather than a screen apiece ─────────────────────────────
 * A report is a query, a date range, a handful of filters and a table. Written
 * as pages, that is the same four things copied fifteen times, and the fifteenth
 * one formats its money differently from the first. Declared here, the filter
 * bar, the table, the totals row, the CSV and the print view are all generated —
 * and adding a report is one entry plus one runner.
 *
 * ── Every report carries its data's own permission ──────────────────────────
 * There is no "may run reports" code. Reading the payroll through a report must
 * need exactly what reading the payroll needs, or the reporting screen becomes
 * the way round the permission system. `HR_PAYROLL` gates the salary report,
 * `TREASURY_VIEW` the caisse ones, and so on down the list.
 */
export const REPORTS: ReportDef[] = [
  // ── Vie scolaire ──────────────────────────────────────────────────────────
  {
    id: "inscriptions",
    section: "vieScolaire",
    labelKey: "inscriptions",
    hintKey: "inscriptions",
    permission: PERMISSIONS.ENROLMENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "level", labelKey: "level", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "enrolledOn", labelKey: "enrolledOn", kind: "date" },
      { key: "status", labelKey: "status", kind: "text" },
    ],
  },
  {
    id: "effectifs",
    section: "vieScolaire",
    labelKey: "effectifs",
    hintKey: "effectifs",
    permission: PERMISSIONS.ENROLMENT_VIEW,
    filters: ["cycle"],
    columns: [
      { key: "level", labelKey: "level", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "boys", labelKey: "boys", kind: "number", total: true },
      { key: "girls", labelKey: "girls", kind: "number", total: true },
      { key: "total", labelKey: "total", kind: "number", total: true },
    ],
  },
  {
    id: "absences",
    section: "vieScolaire",
    labelKey: "absences",
    hintKey: "absences",
    permission: PERMISSIONS.CLASSROOM_ATTENDANCE_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "absences", labelKey: "absences", kind: "number", total: true },
      { key: "lates", labelKey: "lates", kind: "number", total: true },
      { key: "unjustified", labelKey: "unjustified", kind: "number", total: true },
    ],
  },

  {
    id: "non-inscrits",
    section: "vieScolaire",
    labelKey: "notEnrolled",
    hintKey: "notEnrolled",
    permission: PERMISSIONS.STUDENT_VIEW,
    filters: [],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "birthDate", labelKey: "birthDate", kind: "date" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "phone", labelKey: "phone", kind: "text" },
      { key: "status", labelKey: "status", kind: "text" },
    ],
  },
  {
    id: "prescriptions",
    section: "vieScolaire",
    labelKey: "preRegistrations",
    hintKey: "preRegistrations",
    permission: PERMISSIONS.ENROLMENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "level", labelKey: "level", kind: "text" },
      { key: "enrolledOn", labelKey: "enrolledOn", kind: "date" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "phone", labelKey: "phone", kind: "text" },
    ],
  },
  {
    id: "radies",
    section: "vieScolaire",
    labelKey: "withdrawn",
    hintKey: "withdrawn",
    permission: PERMISSIONS.ENROLMENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "status", labelKey: "status", kind: "text" },
      { key: "leftOn", labelKey: "leftOn", kind: "date" },
    ],
  },
  {
    id: "massar",
    section: "vieScolaire",
    labelKey: "massarList",
    hintKey: "massarList",
    permission: PERMISSIONS.STUDENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "massar", labelKey: "massarCode", kind: "text" },
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "pupilAr", labelKey: "pupilAr", kind: "text" },
      { key: "birthDate", labelKey: "birthDate", kind: "date" },
      { key: "class", labelKey: "class", kind: "text" },
    ],
  },
  {
    id: "anciens-nouveaux",
    section: "vieScolaire",
    labelKey: "newAndReturning",
    hintKey: "newAndReturning",
    permission: PERMISSIONS.ENROLMENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "kind", labelKey: "pupilKind", kind: "text" },
      { key: "repeating", labelKey: "repeating", kind: "text" },
    ],
  },
  {
    id: "registre-general",
    section: "vieScolaire",
    labelKey: "generalRegister",
    hintKey: "generalRegister",
    permission: PERMISSIONS.STUDENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "massar", labelKey: "massarCode", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "gender", labelKey: "gender", kind: "text" },
      { key: "birthDate", labelKey: "birthDate", kind: "date" },
      { key: "birthPlace", labelKey: "birthPlace", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "enrolledOn", labelKey: "enrolledOn", kind: "date" },
    ],
  },
  {
    id: "services",
    section: "vieScolaire",
    labelKey: "byService",
    hintKey: "byService",
    permission: PERMISSIONS.ENROLMENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "transport", labelKey: "transport", kind: "text" },
      { key: "canteen", labelKey: "canteen", kind: "text" },
    ],
  },
  {
    id: "allergies",
    section: "vieScolaire",
    labelKey: "allergies",
    hintKey: "allergies",
    permission: PERMISSIONS.STUDENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "bloodType", labelKey: "bloodType", kind: "text" },
      { key: "allergies", labelKey: "allergies", kind: "text" },
      { key: "condition", labelKey: "chronicCondition", kind: "text" },
      { key: "doctor", labelKey: "doctor", kind: "text" },
    ],
  },
  {
    id: "accompagnants",
    section: "vieScolaire",
    labelKey: "guardians",
    hintKey: "guardians",
    permission: PERMISSIONS.FAMILY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "guardian", labelKey: "guardian", kind: "text" },
      { key: "relationship", labelKey: "relationship", kind: "text" },
      { key: "phone", labelKey: "phone", kind: "text" },
      { key: "nationalId", labelKey: "nationalId", kind: "text" },
    ],
  },
  {
    id: "annuaire",
    section: "vieScolaire",
    labelKey: "phoneBook",
    hintKey: "phoneBook",
    permission: PERMISSIONS.FAMILY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "phone", labelKey: "phone", kind: "text" },
      { key: "phoneAlt", labelKey: "phoneAlt", kind: "text" },
      { key: "email", labelKey: "email", kind: "text" },
    ],
  },
  {
    id: "familles",
    section: "vieScolaire",
    labelKey: "familyList",
    hintKey: "familyList",
    permission: PERMISSIONS.FAMILY_VIEW,
    filters: [],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "situation", labelKey: "situation", kind: "text" },
      { key: "city", labelKey: "city", kind: "text" },
      { key: "phone", labelKey: "phone", kind: "text" },
      { key: "children", labelKey: "children", kind: "number", total: true },
    ],
  },
  {
    id: "anniversaires",
    section: "vieScolaire",
    labelKey: "birthdays",
    hintKey: "birthdays",
    permission: PERMISSIONS.STUDENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "day", labelKey: "birthday", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "age", labelKey: "age", kind: "number" },
    ],
  },
  {
    id: "documents-manquants",
    section: "vieScolaire",
    labelKey: "missingDocuments",
    hintKey: "missingDocuments",
    permission: PERMISSIONS.DOCUMENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "missing", labelKey: "missing", kind: "number", total: true },
      { key: "pieces", labelKey: "pieces", kind: "text" },
    ],
  },

  {
    id: "eleves-par-circuit",
    section: "vieScolaire",
    labelKey: "pupilsByRoute",
    hintKey: "pupilsByRoute",
    permission: PERMISSIONS.TRANSPORT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "route", labelKey: "route", kind: "text" },
      { key: "stop", labelKey: "stop", kind: "text" },
      { key: "pickupTime", labelKey: "pickupTime", kind: "text" },
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "direction", labelKey: "direction", kind: "text" },
      { key: "phone", labelKey: "phone", kind: "text" },
    ],
  },
  {
    id: "gasoil-par-vehicule",
    section: "vieScolaire",
    labelKey: "fuelByVehicle",
    hintKey: "fuelByVehicle",
    permission: PERMISSIONS.TRANSPORT_FUEL,
    filters: [],
    columns: [
      { key: "vehicle", labelKey: "vehicle", kind: "text" },
      { key: "date", labelKey: "date", kind: "date" },
      { key: "driver", labelKey: "driver", kind: "text" },
      { key: "litres", labelKey: "litres", kind: "number", total: true },
      { key: "odometer", labelKey: "odometer", kind: "number" },
      { key: "distance", labelKey: "distance", kind: "number", total: true },
      { key: "consumption", labelKey: "consumption", kind: "number" },
      { key: "status", labelKey: "status", kind: "text" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  {
    id: "encaissements",
    section: "finance",
    labelKey: "encaissements",
    hintKey: "encaissements",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "code", labelKey: "receipt", kind: "text" },
      { key: "paidAt", labelKey: "date", kind: "date" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "method", labelKey: "method", kind: "text" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
      { key: "takenBy", labelKey: "takenBy", kind: "text" },
    ],
  },
  {
    id: "decaissements",
    section: "finance",
    labelKey: "decaissements",
    hintKey: "decaissements",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "occurredAt", labelKey: "date", kind: "date" },
      { key: "label", labelKey: "label", kind: "text" },
      { key: "beneficiary", labelKey: "beneficiary", kind: "text" },
      { key: "category", labelKey: "category", kind: "text" },
      { key: "method", labelKey: "method", kind: "text" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "impayes",
    section: "finance",
    labelKey: "impayes",
    hintKey: "impayes",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class", "feeType"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "charged", labelKey: "charged", kind: "money", total: true },
      { key: "paid", labelKey: "collected", kind: "money", total: true },
      { key: "overdue", labelKey: "overdue", kind: "money", total: true },
    ],
  },
  {
    id: "recettes-par-rubrique",
    section: "finance",
    labelKey: "byCategory",
    hintKey: "byCategory",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "category", labelKey: "category", kind: "text" },
      { key: "inCount", labelKey: "movements", kind: "number", total: true },
      { key: "in", labelKey: "moneyIn", kind: "money", total: true },
      { key: "out", labelKey: "moneyOut", kind: "money", total: true },
      { key: "net", labelKey: "net", kind: "money", total: true },
    ],
  },

  {
    id: "echeances-detail",
    section: "finance",
    labelKey: "instalmentDetail",
    hintKey: "instalmentDetail",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class", "feeType"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "service", labelKey: "service", kind: "text" },
      { key: "dueDate", labelKey: "dueOn", kind: "date" },
      { key: "charged", labelKey: "charged", kind: "money", total: true },
      { key: "collected", labelKey: "collected", kind: "money", total: true },
      { key: "balance", labelKey: "balance", kind: "money", total: true },
      { key: "status", labelKey: "status", kind: "text" },
    ],
  },
  {
    id: "releve-journalier",
    section: "finance",
    labelKey: "dailyStatement",
    hintKey: "dailyStatement",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "day", labelKey: "date", kind: "date" },
      { key: "movements", labelKey: "movements", kind: "number", total: true },
      { key: "moneyIn", labelKey: "moneyIn", kind: "money", total: true },
      { key: "moneyOut", labelKey: "moneyOut", kind: "money", total: true },
      { key: "net", labelKey: "net", kind: "money", total: true },
    ],
  },
  {
    id: "releve-mensuel",
    section: "finance",
    labelKey: "monthlyStatement",
    hintKey: "monthlyStatement",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "month", labelKey: "month", kind: "text" },
      { key: "movements", labelKey: "movements", kind: "number", total: true },
      { key: "moneyIn", labelKey: "moneyIn", kind: "money", total: true },
      { key: "moneyOut", labelKey: "moneyOut", kind: "money", total: true },
      { key: "net", labelKey: "net", kind: "money", total: true },
    ],
  },
  {
    id: "releve-annuel",
    section: "finance",
    labelKey: "annualStatement",
    hintKey: "annualStatement",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "year", labelKey: "year", kind: "text" },
      { key: "movements", labelKey: "movements", kind: "number", total: true },
      { key: "moneyIn", labelKey: "moneyIn", kind: "money", total: true },
      { key: "moneyOut", labelKey: "moneyOut", kind: "money", total: true },
      { key: "net", labelKey: "net", kind: "money", total: true },
    ],
  },
  {
    id: "reglements-par-niveau",
    section: "finance",
    labelKey: "paymentsByLevel",
    hintKey: "paymentsByLevel",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle"],
    columns: [
      { key: "level", labelKey: "level", kind: "text" },
      { key: "pupils", labelKey: "pupils", kind: "number", total: true },
      { key: "receipts", labelKey: "receipts", kind: "number", total: true },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "reglements-details",
    section: "finance",
    labelKey: "paymentsDetailed",
    hintKey: "paymentsDetailed",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "receipt", labelKey: "receipt", kind: "text" },
      { key: "date", labelKey: "date", kind: "date" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "service", labelKey: "service", kind: "text" },
      { key: "period", labelKey: "period", kind: "text" },
      { key: "method", labelKey: "method", kind: "text" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "reglements-par-service",
    section: "finance",
    labelKey: "paymentsByService",
    hintKey: "paymentsByService",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "service", labelKey: "service", kind: "text" },
      { key: "pupils", labelKey: "pupils", kind: "number", total: true },
      { key: "lines", labelKey: "lines", kind: "number", total: true },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "synthese-annuelle",
    section: "finance",
    labelKey: "annualSummary",
    hintKey: "annualSummary",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "month", labelKey: "month", kind: "text" },
      { key: "receipts", labelKey: "receipts", kind: "number", total: true },
      { key: "families", labelKey: "families", kind: "number" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "releve-caisse",
    section: "finance",
    labelKey: "cashStatement",
    hintKey: "cashStatement",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "openedAt", labelKey: "openedOn", kind: "date" },
      { key: "register", labelKey: "register", kind: "text" },
      { key: "holder", labelKey: "holder", kind: "text" },
      { key: "openingFloat", labelKey: "openingFloat", kind: "money", total: true },
      { key: "expected", labelKey: "expected", kind: "money", total: true },
      { key: "counted", labelKey: "counted", kind: "money", total: true },
      { key: "variance", labelKey: "variance", kind: "money", total: true },
      { key: "status", labelKey: "status", kind: "text" },
    ],
  },
  {
    id: "reglements-par-eleve",
    section: "finance",
    labelKey: "paymentsByPupil",
    hintKey: "paymentsByPupil",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "receipts", labelKey: "receipts", kind: "number", total: true },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "paiements-par-eleve",
    section: "finance",
    labelKey: "pupilPaymentList",
    hintKey: "pupilPaymentList",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "receipt", labelKey: "receipt", kind: "text" },
      { key: "date", labelKey: "date", kind: "date" },
      { key: "method", labelKey: "method", kind: "text" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "attestation-paiement",
    section: "finance",
    labelKey: "paymentCertificate",
    hintKey: "paymentCertificate",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "charged", labelKey: "charged", kind: "money", total: true },
      { key: "collected", labelKey: "collected", kind: "money", total: true },
      { key: "lastPaidOn", labelKey: "lastPaidOn", kind: "date" },
    ],
  },
  {
    id: "synthese-periodique",
    section: "finance",
    labelKey: "periodSummary",
    hintKey: "periodSummary",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class", "feeType"],
    columns: [
      { key: "period", labelKey: "period", kind: "text" },
      { key: "lines", labelKey: "lines", kind: "number", total: true },
      { key: "charged", labelKey: "charged", kind: "money", total: true },
      { key: "collected", labelKey: "collected", kind: "money", total: true },
      { key: "balance", labelKey: "balance", kind: "money", total: true },
    ],
  },
  {
    id: "reglements-cheque",
    section: "finance",
    labelKey: "chequePayments",
    hintKey: "chequePayments",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "date", labelKey: "date", kind: "date" },
      { key: "receipt", labelKey: "receipt", kind: "text" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "bank", labelKey: "bank", kind: "text" },
      { key: "chequeNumber", labelKey: "chequeNumber", kind: "text" },
      { key: "dueOn", labelKey: "dueOn", kind: "date" },
      { key: "chequeStatus", labelKey: "chequeStatus", kind: "text" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "reglements-espece",
    section: "finance",
    labelKey: "cashPayments",
    hintKey: "cashPayments",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "date", labelKey: "date", kind: "date" },
      { key: "receipt", labelKey: "receipt", kind: "text" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "takenBy", labelKey: "takenBy", kind: "text" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "reductions-par-service",
    section: "finance",
    labelKey: "discountsByService",
    hintKey: "discountsByService",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "service", labelKey: "service", kind: "text" },
      { key: "lines", labelKey: "lines", kind: "number", total: true },
      { key: "base", labelKey: "base", kind: "money", total: true },
      { key: "reduction", labelKey: "reduction", kind: "money", total: true },
      { key: "charged", labelKey: "charged", kind: "money", total: true },
    ],
  },
  {
    id: "echeances-payees",
    section: "finance",
    labelKey: "instalmentsSettled",
    hintKey: "instalmentsSettled",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class", "feeType"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "service", labelKey: "service", kind: "text" },
      { key: "dueDate", labelKey: "dueOn", kind: "date" },
      { key: "paidOn", labelKey: "paidOn", kind: "date" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "echeances-impayees",
    section: "finance",
    labelKey: "instalmentsUnpaid",
    hintKey: "instalmentsUnpaid",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class", "feeType"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "service", labelKey: "service", kind: "text" },
      { key: "dueDate", labelKey: "dueOn", kind: "date" },
      { key: "charged", labelKey: "charged", kind: "money", total: true },
      { key: "collected", labelKey: "collected", kind: "money", total: true },
      { key: "balance", labelKey: "balance", kind: "money", total: true },
      { key: "daysLate", labelKey: "daysLate", kind: "number" },
    ],
  },
  {
    id: "echeances-impayees-matricule",
    section: "finance",
    labelKey: "unpaidByMatricule",
    hintKey: "unpaidByMatricule",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "lines", labelKey: "lines", kind: "number", total: true },
      { key: "oldestDue", labelKey: "oldestDue", kind: "date" },
      { key: "daysLate", labelKey: "daysLate", kind: "number" },
      { key: "balance", labelKey: "balance", kind: "money", total: true },
    ],
  },
  {
    id: "recettes-depenses",
    section: "finance",
    labelKey: "cashBook",
    hintKey: "cashBook",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "date", labelKey: "date", kind: "date" },
      { key: "label", labelKey: "label", kind: "text" },
      { key: "category", labelKey: "category", kind: "text" },
      { key: "method", labelKey: "method", kind: "text" },
      { key: "moneyIn", labelKey: "moneyIn", kind: "money", total: true },
      { key: "moneyOut", labelKey: "moneyOut", kind: "money", total: true },
    ],
  },
  {
    id: "relances",
    section: "finance",
    labelKey: "dunning",
    hintKey: "dunning",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "phone", labelKey: "phone", kind: "text" },
      { key: "oldestDue", labelKey: "oldestDue", kind: "date" },
      { key: "daysLate", labelKey: "daysLate", kind: "number" },
      { key: "balance", labelKey: "balance", kind: "money", total: true },
    ],
  },
  {
    id: "cheques-par-etat",
    section: "finance",
    labelKey: "chequesByStatus",
    hintKey: "chequesByStatus",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "chequeStatus", labelKey: "chequeStatus", kind: "text" },
      { key: "chequeNumber", labelKey: "chequeNumber", kind: "text" },
      { key: "bank", labelKey: "bank", kind: "text" },
      { key: "drawer", labelKey: "drawer", kind: "text" },
      { key: "dueOn", labelKey: "dueOn", kind: "date" },
      { key: "depositedOn", labelKey: "depositedOn", kind: "date" },
      { key: "settledOn", labelKey: "settledOn", kind: "date" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "annulations-services",
    section: "finance",
    labelKey: "serviceCancellations",
    hintKey: "serviceCancellations",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: ["cycle", "level", "class", "feeType"],
    columns: [
      { key: "cancelledOn", labelKey: "cancelledOn", kind: "date" },
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "service", labelKey: "service", kind: "text" },
      { key: "status", labelKey: "status", kind: "text" },
      { key: "reason", labelKey: "reason", kind: "text" },
      { key: "cancelledBy", labelKey: "cancelledBy", kind: "text" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },
  {
    id: "reglements-annules",
    section: "finance",
    labelKey: "cancelledPayments",
    hintKey: "cancelledPayments",
    permission: PERMISSIONS.TREASURY_VIEW,
    filters: [],
    columns: [
      { key: "receipt", labelKey: "receipt", kind: "text" },
      { key: "date", labelKey: "date", kind: "date" },
      { key: "cancelledOn", labelKey: "cancelledOn", kind: "date" },
      { key: "family", labelKey: "family", kind: "text" },
      { key: "reason", labelKey: "reason", kind: "text" },
      { key: "takenBy", labelKey: "takenBy", kind: "text" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
    ],
  },

  // ── Ressources humaines ───────────────────────────────────────────────────
  {
    id: "paie",
    section: "rh",
    labelKey: "payroll",
    hintKey: "payroll",
    permission: PERMISSIONS.HR_PAYROLL,
    filters: ["staff"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "staff", labelKey: "employee", kind: "text" },
      { key: "period", labelKey: "period", kind: "text" },
      { key: "gross", labelKey: "gross", kind: "money", total: true },
      { key: "deductions", labelKey: "deductions", kind: "money", total: true },
      { key: "net", labelKey: "net", kind: "money", total: true },
      { key: "status", labelKey: "status", kind: "text" },
    ],
  },
  {
    id: "avances",
    section: "rh",
    labelKey: "advances",
    hintKey: "advances",
    permission: PERMISSIONS.HR_PAYROLL,
    filters: ["staff"],
    columns: [
      { key: "staff", labelKey: "employee", kind: "text" },
      { key: "requestedOn", labelKey: "date", kind: "date" },
      { key: "amount", labelKey: "amount", kind: "money", total: true },
      { key: "recovered", labelKey: "recovered", kind: "money", total: true },
      { key: "outstanding", labelKey: "outstanding", kind: "money", total: true },
      { key: "status", labelKey: "status", kind: "text" },
    ],
  },
  {
    id: "presence-personnel",
    section: "rh",
    labelKey: "staffAttendance",
    hintKey: "staffAttendance",
    permission: PERMISSIONS.HR_VIEW,
    filters: ["staff"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "staff", labelKey: "employee", kind: "text" },
      { key: "present", labelKey: "present", kind: "number", total: true },
      { key: "absent", labelKey: "absences", kind: "number", total: true },
      { key: "late", labelKey: "lates", kind: "number", total: true },
    ],
  },

  // ── Scolarité ─────────────────────────────────────────────────────────────
  {
    id: "resultats",
    section: "academics",
    labelKey: "results",
    hintKey: "results",
    permission: PERMISSIONS.ASSESSMENT_VIEW,
    filters: ["cycle", "level", "class"],
    columns: [
      { key: "code", labelKey: "code", kind: "text" },
      { key: "pupil", labelKey: "pupil", kind: "text" },
      { key: "class", labelKey: "class", kind: "text" },
      { key: "marked", labelKey: "marksEntered", kind: "number", total: true },
      { key: "average", labelKey: "average", kind: "number" },
    ],
  },
];

export function findReport(id: string): ReportDef | undefined {
  return REPORTS.find((report) => report.id === id);
}
