import {
  FileBarChartIcon,
  ArrowLeftRightIcon,
  BackpackIcon,
  BanknoteArrowDownIcon,
  BanknoteArrowUpIcon,
  BusIcon,
  BriefcaseIcon,
  BuildingIcon,
  CalendarCheckIcon,
  CalendarClockIcon,
  CalendarOffIcon,
  ClipboardCheckIcon,
  ScrollTextIcon,
  CalendarRangeIcon,
  ContactIcon,
  MessageSquareTextIcon,
  NotebookPenIcon,
  PresentationIcon,
  GraduationCapIcon,
  CalendarHeartIcon,
  HeartHandshakeIcon,
  HomeIcon,
  LayersIcon,
  LayoutDashboardIcon,
  MapPinnedIcon,
  PaletteIcon,
  ReceiptTextIcon,
  RouteIcon,
  SchoolIcon,
  SettingsIcon,
  ShieldCheckIcon,
  UserIcon,
  UsersIcon,
  WalletCardsIcon,
  WalletIcon,
} from "lucide-react";

import type { NavIcon } from "@/lib/module";

/**
 * Maps the icon *names* modules use in their manifests to real components.
 *
 * The indirection exists because nav entries cross the server/client boundary —
 * the sidebar is filtered on the server and a component is not serialisable.
 * Adding an icon is a two-step change: the name in `lib/module.ts` (`NavIcon`)
 * and the mapping here. `Record<NavIcon, …>` makes forgetting the second half a
 * compile error.
 */
export const NAV_ICONS: Record<NavIcon, typeof LayoutDashboardIcon> = {
  dashboard: LayoutDashboardIcon,
  reports: FileBarChartIcon,
  organization: BuildingIcon,
  schools: SchoolIcon,
  schoolYears: CalendarRangeIcon,
  users: UsersIcon,
  roles: ShieldCheckIcon,
  profile: UserIcon,
  appearance: PaletteIcon,
  configuration: SettingsIcon,
  audit: ScrollTextIcon,
  hr: BriefcaseIcon,
  schoolLife: HeartHandshakeIcon,
  events: CalendarHeartIcon,
  students: GraduationCapIcon,
  families: HomeIcon,
  classes: LayersIcon,
  assessments: ClipboardCheckIcon,
  supplies: BackpackIcon,
  timetable: CalendarClockIcon,
  cashRegister: WalletIcon,
  encaissement: BanknoteArrowDownIcon,
  decaissement: BanknoteArrowUpIcon,
  transfert: ArrowLeftRightIcon,
  cheques: ReceiptTextIcon,
  registers: WalletCardsIcon,
  transport: BusIcon,
  routes: RouteIcon,
  fleet: BusIcon,
  zones: MapPinnedIcon,
  staff: ContactIcon,
  attendance: CalendarCheckIcon,
  payroll: BanknoteArrowUpIcon,
  leave: CalendarOffIcon,
  teacher: PresentationIcon,
  homework: NotebookPenIcon,
  remarks: MessageSquareTextIcon,
};
